(ns abroker.ibkr.codes
  (:require [clojure.set :as set]))

;; many of these codes were adapted from https://github.com/alex314159/ib-re-actor-976-plus


(def tick-fields-by-key
  ; https://www.interactivebrokers.com/campus/ibkr-api-page/twsapi-doc/#available-tick-types
  {:bid-size                     0
   :bid-price                    1
   :ask-price                    2
   :ask-size                     3
   :last-price                   4
   :last-size                    5
   :high                         6
   :low                          7
   :volume                       8
   :close                        9
   :bid-option-computation       10
   :ask-option-computation       11
   :last-option-computation      12
   :model-option-computation     13
   :open                         14
   :low-13-week                  15
   :high-13-week                 16
   :low-26-week                  17
   :high-26-week                 18
   :low-52-week                  19
   :high-52-week                 20
   :avg-volume                   21
   :open-interest                22
   :option-historical-volatility 23
   :option-implied-volatility    24
   :option-bid-exchange          25
   :option-ask-exchange          26
   :option-call-open-interest    27
   :option-put-open-interest     28
   :option-call-volume           29
   :option-put-volume            30
   :index-future-premium         31
   :bid-exchange                 32
   :ask-exchange                 33
   :auction-volume               34
   :auction-price                35
   :auction-imbalance            36
   :mark-price                   37
   :bid-efp-computation          38
   :ask-efp-computation          39
   :last-efp-computation         40
   :open-efp-computation         41
   :high-efp-computation         42
   :low-efp-computation          43
   :close-efp-computation        44
   :last-timestamp               45
   :shortable                    46
   :fundamental-ratios           47
   :realtime-volume              48
   :halted                       49
   :bid-yield                    50
   :ask-yield                    51
   :last-yield                   52
   :cust-option-computation      53
   :trade-count                  54
   :trade-rate                   55
   :volume-rate                  56
   :last-rth-trade               57
   :rt-historical-vol            58
   :ib-dividends                 59
   :bond-factor-multiplier       60
   :regulatory-imbalance         61
   :news-tick                    62
   :short-term-volume-3-min      63
   :short-term-volume-5-min      64
   :short-term-volume-10-min     65
   :delayed-bid                  66
   :delayed-ask                  67
   :delayed-last                 68
   :delayed-bid-size             69
   :delayed-ask-size             70
   :delayed-last-size            71
   :delayed-high                 72
   :delayed-low                  73
   :delayed-volume               74
   :delayed-close                75
   :delayed-open                 76
   :rt-trd-volume                77
   :creditman-mark-price         78
   :creditman-slow-mark-price    79
   :delayed-bid-option           80
   :delayed-ask-option           81
   :delayed-last-option          82
   :delayed-model-option         83
   :last-exch                    84
   :last-reg-time                85
   :futures-open-interest        86
   :avg-opt-volume               87
   :delayed-last-timestamp       88
   :shortable-shares             89
   :delayed-halted               90
   :reuters-2-mutual-funds       91
   :etf-nav-close                92
   :etf-nav-bid                  94
   :etf-nav-ask                  95
   :etf-nav-last                 96
   :etf-frozen-nav-last          97
   :etf-nav-high                 98
   :etf-nav-low                  99
   :social-market-analytics     100
   :estimated-ipo-midpoint      101
   :final-ipo-last              102
   :delayed-yield-bid           103
   :delayed-yield-ask           104})

(def tick-fields-by-code
  (set/map-invert tick-fields-by-key))

; maps ibkr's sec-type to our instrument-type
(def instrument-type
  {""        :none
   "STK"     :stock
   "OPT"     :option
   "FUT"     :future
   "CONTFUT" :continuous-future
   "CASH"    :cash
   "BOND"    :bond
   "CFD"     :cfd
   "FOP"     :future-option
   "WAR"     :warrant
   "IOPT"    :iopt
   "FWD"     :fwd
   "BAG"     :bag
   "IND"     :index
   "BILL"    :bill
   "FUND"    :fund
   "FIXED"   :fixed
   "SLB"     :slb
   "NEWS"    :news
   "CMDTY"   :commodity
   "BSK"     :bsk
   "ICU"     :icu
   "ICS"     :ics
   "CRYPTO"  :crypto})

; maps our instrument-type to ibkr's sec-type
(def sec-type
  (set/map-invert instrument-type))
